version: '3.8'

services:

  lab-bash:
    image: debian:stable-slim
    container_name: debian_lab
    tty: true
    stdin_open: true

  database:
    image: mysql:8.0
    container_name: mysql_server

    environment:
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3306:3306"
      